language: node_js
node_js:
  - "node"
script:
  - npm run lint
  - npm test
  - npm run check
addons:
  code_climate:
    repo_token: 5491c8fccad611cd0df73170678f76ccc322c02c9676d755e5739eada53dc600

after_script:
  - npm run codeclimate

# whitelist
branches:
  only:
    - master