language: node_js
node_js:
  - "node"
script:
  - npm run lint
  - npm test
  - npm run check
addons:
  code_climate:
    repo_token: CODECLIMATE_REPO_TOKEN=4aaa7dac0e1935490d15a203b020d8f6cb3d52aa0b61ee5aa100fe9fc4b5e1ef

after_script:
  - codeclimate-test-reporter < lcov.info

# whitelist
branches:
  only:
    - master